"use client";

import MaxWidthWrapper from "@/components/MaxWidthWrapper";
import Image from "next/image";


export default function PrivacyPolicy() {
  return (
    <MaxWidthWrapper>
      <div className="xl:py-24 py-12">
  <div className="mx-auto max-w-7xl px-6 xl:px-8">
    <div className="mx-auto max-w-4xl xl:mx-0">
      <h2 className="text-base font-semibold leading-7 text-red-500">
        Privacy Policy
      </h2>
      <h4 className="mt-2 text-xl font-bold tracking-tight text-gray-900">
        Last updated: September 03, 2024
      </h4>
      <p className="mt-6 text-xl leading-8 text-gray-600">
        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
      </p>
      <p className="mt-6 text-xl leading-8 text-gray-600">
        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
      </p>
      <p className="mt-6 text-xl leading-8 text-gray-600">
        This Privacy Policy has been created with the help of the Privacy Policy Generator.
      </p>

      <h3 className="mt-10 text-xl font-bold tracking-tight text-gray-900">Interpretation and Definitions</h3>
      <p className="mt-6 text-xl leading-8 text-gray-600">
        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </p>

      <h3 className="mt-10 text-xl font-bold tracking-tight text-gray-900">Definitions</h3>
      <p className="mt-6 text-xl leading-8 text-gray-600">For the purposes of this Privacy Policy:</p>

      <ul className="mt-6 text-xl leading-8 text-gray-600 list-disc list-inside space-y-2">
        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where control means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
        <li><strong>Application</strong> refers to Romania Online, the software program provided by the Company.</li>
        <li><strong>Company</strong> (referred to as either the Company, We, Us or Our) refers to ROL Media LTD, 35 Bankhead Place, Airdrie. ML68JW.</li>
        <li><strong>Cookies</strong> are small files that are placed on Your device by a website, containing browsing details.</li>
        <li><strong>Country</strong> refers to: United Kingdom</li>
        <li><strong>Device</strong> means any device that can access the Service such as a computer, cellphone or a tablet.</li>
        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
        <li><strong>Service</strong> refers to the Application or the Website or both.</li>
        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
        <li><strong>Website</strong> refers to Romania Online, accessible from <a href="http://www.romaniaonline.net" className="text-blue-600 underline">romaniaonline.net</a></li>
        <li><strong>You</strong> means the individual accessing or using the Service, or a legal entity on behalf of which such individual is accessing or using the Service.</li>
      </ul>

      <h3 className="mt-10 text-xl font-bold tracking-tight text-gray-900">Collecting and Using Your Personal Data</h3>
      <h4 className="mt-8 text-xl font-semibold tracking-tight text-gray-800">Types of Data Collected</h4>
      <p className="mt-6 text-xl leading-8 text-gray-600"><strong>Personal Data</strong>: While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You.</p>
      <ul className="mt-4 text-xl leading-8 text-gray-600 list-disc list-inside">
        <li>Usage Data</li>
      </ul>

      <h4 className="mt-8 text-xl font-semibold tracking-tight text-gray-800">Usage Data</h4>
      <p className="mt-6 text-xl leading-8 text-gray-600">
        Usage Data is collected automatically when using the Service. It may include information such as Your IP address, browser type, browser version, pages visited, time and date of visit, time spent on pages, unique device identifiers and other diagnostic data.
      </p>
      <p className="mt-6 text-xl leading-8 text-gray-600">
        When You access the Service by or through a mobile device, We may collect certain additional information automatically, such as mobile device type, unique ID, IP address, OS, and browser type.
      </p>

      <h4 className="mt-8 text-xl font-semibold tracking-tight text-gray-800">Tracking Technologies and Cookies</h4>
      <p className="mt-6 text-xl leading-8 text-gray-600">
        We use Cookies and similar tracking technologies to track activity on Our Service and store certain information.
      </p>
      <ul className="mt-4 text-xl leading-8 text-gray-600 list-disc list-inside">
        <li><strong>Cookies or Browser Cookies</strong>: Small files placed on Your device. You can configure your browser to refuse Cookies.</li>
        <li><strong>Web Beacons</strong>: Small electronic files in emails or web pages to monitor user behavior like email opens or site visits.</li>
      </ul>

      <h3 className="mt-10 text-xl font-bold tracking-tight text-gray-900">Use of Your Personal Data</h3>
      <ul className="mt-6 text-xl leading-8 text-gray-600 list-disc list-inside space-y-2">
        <li>To provide and maintain our Service</li>
        <li>To manage Your Account</li>
        <li>To perform a contract</li>
        <li>To contact You via various communication methods</li>
        <li>To send you news, offers, and similar content unless opted out</li>
        <li>To manage Your requests</li>
        <li>For business transfers, analysis, improvements, and marketing</li>
      </ul>

      <h3 className="mt-10 text-xl font-bold tracking-tight text-gray-900">Retention and Transfer of Your Data</h3>
      <p className="mt-6 text-xl leading-8 text-gray-600">
        We will retain Your Personal Data only as long as necessary and in accordance with legal obligations. Transfers may occur to jurisdictions with different data protection laws.
      </p>

      <h3 className="mt-10 text-xl font-bold tracking-tight text-gray-900">Delete Your Personal Data</h3>
      <p className="mt-6 text-xl leading-8 text-gray-600">
        You can delete or request deletion of your data at any time, except where legally required to retain it. Account settings or direct contact can be used for requests.
      </p>

      <h3 className="mt-10 text-xl font-bold tracking-tight text-gray-900">Disclosure of Your Personal Data</h3>
      <ul className="mt-6 text-xl leading-8 text-gray-600 list-disc list-inside space-y-2">
        <li>For business transactions like mergers or acquisitions</li>
        <li>To law enforcement when legally required</li>
        <li>To comply with legal obligations and protect rights or safety</li>
      </ul>

      <h3 className="mt-10 text-xl font-bold tracking-tight text-gray-900">Security</h3>
      <p className="mt-6 text-xl leading-8 text-gray-600">
        We use commercially acceptable means to protect Your Personal Data, but no system is 100% secure.
      </p>

      <h3 className="mt-10 text-xl font-bold tracking-tight text-gray-900">Children Privacy</h3>
      <p className="mt-6 text-xl leading-8 text-gray-600">
        Our Service is not intended for anyone under the age of 13. We do not knowingly collect data from children without parental consent.
      </p>

      <h3 className="mt-10 text-xl font-bold tracking-tight text-gray-900">Links to Other Websites</h3>
      <p className="mt-6 text-xl leading-8 text-gray-600">
        Our Service may contain links to other websites. We are not responsible for the privacy practices or content of those sites.
      </p>

      <h3 className="mt-10 text-xl font-bold tracking-tight text-gray-900">Changes to this Privacy Policy</h3>
      <p className="mt-6 text-xl leading-8 text-gray-600">
        We may update this Privacy Policy. Changes will be posted here and notified through email or our Service.
      </p>

      <h3 className="mt-10 text-xl font-bold tracking-tight text-gray-900">Contact Us</h3>
      <p className="mt-6 text-xl leading-8 text-gray-600">
        If you have any questions about this Privacy Policy, you can contact us by email: <a href="mailto:social.at.romaniaonline@gmail.com" className="text-blue-600 underline">social.at.romaniaonline@gmail.com</a>
      </p>
    </div>
  </div>
</div>
    </MaxWidthWrapper>
  )
}